name: saludo-color 🌈

on:
  pull_request:
  workflow_dispatch:

env:
  SALUDO: "Hola "
  RED: \033[31m
  GREEN: \033[32m
  YELLOW: \033[33m
  BLUE: \033[34m
  PINK: \033[35m
  CYAN: \033[36m
  WHITE: \033[37m
  NORMAL: \033[0;39m

jobs:
  pruebas:
    name: Pruebas 🏗️
    runs-on: ubuntu-latest
    env:
      NOMBRE: Mundo

    steps:
      - name: Checkout repository 🛎️
        uses: actions/checkout@v4

      - name: Decir hola 👋
        run: |
          echo -e "$RED $SALUDO$NOMBRE. Hoy es $DIA! red"
          echo -e "$GREEN $SALUDO$NOMBRE. Hoy es $DIA! green"
          echo -e "$YELLOW $SALUDO$NOMBRE. Hoy es $DIA! yellow"
          echo -e "$BLUE $SALUDO$NOMBRE. Hoy es $DIA! blue"
          echo -e "$PINK $SALUDO$NOMBRE. Hoy es $DIA! pink"
          echo -e "$CYAN $SALUDO$NOMBRE. Hoy es $DIA! cyan"
          echo -e "$WHITE $SALUDO$NOMBRE. Hoy es $DIA! white"
          echo -e "$NORMAL $SALUDO$NOMBRE. Hoy es $DIA! normal"
          echo -e ""$NORMAL $SALUDO$RED$NOMBRE. $GREEN Hoy es $YELLOW$DIA! varios""
        env:
          DIA: Lunes

  paralelo:
    name: Paralelo 🐳
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository 🛎️
        uses: actions/checkout@v4

      - name: Ejecutar en paralelo 🚅
        run: echo -e "$GREEN Hola desde un contenedor! $NORMAL"

      - name: Recoger información del contenedor 📝
        run: |
          whoami > info.txt
          free -h >> info.txt
          ps aux >> info.txt
          cat info.txt
      - name: Upload info.txt 📤
        uses: actions/upload-artifact@v4
        with:
          name: info
          path: ./info.txt
  
  check-bats-version:
    runs-on: ubuntu-latest
    needs: paralelo
    steps:
      - name: Checkout repository 🛎️
        uses: actions/checkout@v4
      - name: Setup Node.js 🚀
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Bats 🦇
        run: npm install -g bats
      - name: Check Bats version 🦇
        run: bats -v
      - name: Download info.txt 📥
        uses: actions/download-artifact@v4
        with:
          name: info
          path: ./info.txt
      - name: Ejecutar test de Bats 🦇
        run: bats test.bats
