apiVersion: apps/v1
kind: Deployment
metadata:
  name: practica-4-v2
spec:
  selector:
    matchLabels:
      app: frontend-v2
  template:
    metadata:
      labels:
        app: frontend-v2
    spec:
      containers:
      - name: pod-practica-v2
        image: frmadem/catro-eixos-k8s-ej1:v2
        command: ["npm","run","iniciar"]
        env:
          - name: PUERTO_APP
            value: "8080"
        ports:
        - containerPort: 8080