#bbdd-volume.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-db-pv-claim
  namespace: "wp-release2"
  labels:
    app: deploy-wp-bbdd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
            storage: 2Gi

