# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: "{{ .Values.namespace }}"
type: Opaque
data:
  root-password: QzBudHI0c2VuNA==
  user-password: VXNlckMwbnRyNHNlbjQK