apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Release.Name }}-ingress
  annotations:
          #kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /{{ .Release.Name }}
        backend:
          service:
            name: {{ .Release.Name }}-service
            port: 80
