apiVersion: apps/v1
kind: Deployment
metadata:
  name:  deploy-{{ .Release.Name }}-ghost
  #namespace: default
  labels:
    app:  ghost-{{ .Release.Name }}-worker
spec:
  selector:
    matchLabels:
      app: ghost-{{ .Release.Name }}-worker
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  ghost-{{ .Release.Name }}-worker
    spec:
      containers:
      - name:  ghost-{{ .Release.Name }}-worker
        image: {{ .Values.image.deploy}}
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 300m
            memory: 256Mi
        livenessProbe:
          tcpSocket:
            port: 2368
          initialDelaySeconds: 50
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 2368
          initialDelaySeconds: 50
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10

        envFrom:
          - configMapRef: 
              name: deploy-{{ .Release.Name }}-configmap
        env:
        - name: private_key
          valueFrom:
            secretKeyRef:
              name: deploy-{{ .Release.Name }}-secret
              key: private_key
        ports:
        - containerPort:  2368

      restartPolicy: Always