apiVersion: v1
kind: Service
metadata:
  name: service-{{ .Release.Name }}-ghost
  #namespace: default
spec:
  selector:
    app: ghost-{{ .Release.Name }}-worker
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 2368
    protocol: TCP
    #nodePort: 