images:
    wordpress: "kastras/wordpress:0.0.5"
    mysql: "mysql:5.7"

mysql:
    DB_BBDD: "wordpress"
    DB_USER: "wordpress-user"
    DB_PASSWORD: "3EDCfR4-5DDS"
    DB_ROOT_PASSWORD: "845JXSD128sdk"

namespace: "r-castrelo"

volumes:
    mysql: mysql-disck
    wordpress: wp-content

nfs:
  wordpress:
    ip: 10.200.2.130
    path: /wp_content
  storage: 1T

ingress-nginx:
 controller:
   scope:
     enabled: true # defaults to .Release.Namespace
#Ajustes para Google Cloud 
   service:
     internal:
       enabled: true
       annotations:
         # Create internal LB
         cloud.google.com/load-balancer-type: "Internal"
         # Any other annotation can be declared here.
