# bbdd-service.yaml

kind: Service
apiVersion: v1
metadata:  # esta é a parte de identificación do servizo
<<<<<<< HEAD
  name: servizo-{{ .Release.Name }}-bbdd
=======
  name: servizo-meiga-bbdd
>>>>>>> 02142c9ff036ec5a38a4ead91cd7592bba1fdd85
spec:
  selector:   # esta é a parte de selección
    app: meiga-mysql
  ports:  # esta é a parte de especificación propia
  - protocol: TCP
    port: 3306
    targetPort: 3306