# deployment_1.yaml
apiVersion: apps/v1
kind: Deployment  # esta parte define o Deployment
metadata:
  name: despregue-{{ .Release.Name }}-bbdd
  labels:
    app: meiga-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meiga-mysql
  template: # a partir de aquí definimos o pod
    metadata:
      labels:
        app: meiga-mysql
    spec:
      containers:
      - name: meiga-mysql
        image: {{ .Values.imagenes.bbdd }}
        env:
          - name: "MYSQL_ROOT_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-secrets
                key: root-password
            
          - name: "MYSQL_DATABASE"
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: "MYSQL_DATABASE"
        ports:
        - containerPort: 3306