# despregue-practica-1.yaml

apiVersion: apps/v1
kind: Deployment  # esta parte define o Deployment
metadata:
  name: despregue-practica-1
  labels:
    app: practica1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: practica1
  template: # a partir de aquí definimos o pod
    metadata:
      labels:
        app: practica1
    spec:
      containers:
      - name: frmadem
        image: frmadem/catro-eixos-k8s-ej1:v1 # este é o cambio!!!!
        command: ["npm", "run", "iniciar"]
        env:
          - name: PUERTO_APP
            value: "80"
        ports:
          - containerPort: 80
