apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.volumes.mysql }}"
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard
