#service-mysql.yaml
apiVersion: v1
kind: Service
metadata:
  name: service-{{ .Release.Name }}-mysql
  labels: 
    app: {{ .Release.Name }}-wp
spec:
  ports:
    - port: {{ .Values.ports.containerPort_mysql }}
  selector:
    app: {{ .Release.Name }}-wp
    tier: mysql
