<<<<<<< HEAD
# bbdd-deploy.yaml
=======
# deployment_1.yaml
>>>>>>> 02142c9ff036ec5a38a4ead91cd7592bba1fdd85
apiVersion: apps/v1
kind: Deployment  # esta parte define o Deployment
metadata:
  name: despregue-meiga-bbdd
  labels:
    app: meiga-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meiga-mysql
  template: # a partir de aquí definimos o pod
    metadata:
      labels:
        app: meiga-mysql
    spec:
      containers:
      - name: meiga-mysql
        image: mysql:5.7
        env:
          - name: "MYSQL_ROOT_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: meiga-secrets
                key: root-password
            
          - name: "MYSQL_DATABASE"
            valueFrom:
              configMapKeyRef:
                name: "meiga-config"
                key: "MYSQL_DATABASE"
        ports:
        - containerPort: 3306