# configmap.yaml
#
apiVersion: v1
kind: ConfigMap # o tipo de artefacto
metadata:
  name: meiga-config # ten un nome
  labels:
    tipo: "configuracions"  # podemoslle meter labels
data:
  CURSO: "nomeCurso"
  DOCENTE: "nomeAlumno"
  MYSQL_HOST: servizo-meiga-bbdd
  MYSQL_USER: "root"
  MYSQL_DATABASE: "meiga"