apiVersion: v1
kind: Service
metadata:
  name: service-{{ .Release.Name }}-mysql
  namespace: "{{ .Values.namespace }}"
spec:
  selector:
    app: mysql-wordpress
  ports:
  - protocol: TCP
    port: 3306