#service-wordpress.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: p-sanchez
  name: wordpress-service
  labels:
    app: wordpress
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  selector:
    app: wordpress
    tier: frontend
