kind: ConfigMap
apiVersion: v1
metadata:
  name: mariadb
  namespace: mariadb

auth:
  rootPassword: "gustavo"
  database: "datos-maria"
  username: "r-castrelo"
  password: "r-castrelo"

primary:
  persistence:
    enabled: false
  service:
    port: "3500"

secondary:
  persistence:
    enabled: false
