kind: Pod
apiVersion: v1
metadata:
  name: pod-practica-2
spec:
  containers:
    - name: container-web
      image: frmadem/catro-eixos-k8s-ej1:v1
      command: ["npm","run","iniciar"]
      resources:
        requests:
          memory: "48Mi"
          cpu: "150m"
        limits:
          memory: "64Mi"
          cpu: "200m"
      env:
        - name : PUERTO_APP
          value : "80"
        - name : "RUTA_LOGS"
          value: "/var/log"
      volumeMounts:
        - mountPath: /var/log
          name: volume-logs
      ports:
      - containerPort: 80
      imagePullPolicy: Always
      readinessProbe:
        httpGet:
          path: /servidor
          port: 80
        initialDelaySeconds: 15
        periodSeconds: 5
      livenessProbe:
        httpGet:
          path: /servidor
          port: 80
        initialDelaySeconds: 20
        periodSeconds: 10

  volumes:
    - name: volume-logs
      hostPath:
        path: /tmp/k8s_logs
        type: DirectoryOrCreate
