# bbdd-service.yaml

kind: Service
apiVersion: v1
metadata:  # esta é a parte de identificación do servizo
  name: servizo-meiga-bbdd
spec:
  selector:   # esta é a parte de selección
    app: meiga-mysql
  ports:  # esta é a parte de especificación propia
  - protocol: TCP
    port: 3306
    targetPort: 3306