# configmap.yaml
#
apiVersion: v1
kind: ConfigMap # o tipo de artefacto
metadata:
  name: meiga-config # ten un nome
  labels:
    tipo: "configuracions"  # podemoslle meter labels
data:
  CURSO: "nomeCurso" # aquí temos clave=valor como configuración
  DOCENTE: "nomeDocente"
  MYSQL_HOST: "servizo-meiga-bbdd:3306"
  MYSQL_USER: "root"
  MYSQL_DATABASE: "meiga"